window.addEventListener('DOMContentLoaded', main);  // initiate here.

function main() {

    const postBtn = document.getElementById("postBtn");
    const getBtn = document.getElementById("getBtn");
    const putBtn = document.getElementById("putBtn");
    const deleteBtn = document.getElementById("deleteBtn");

    const postBtnFetch = document.getElementById("postBtnFetch");
    const getBtnFetch = document.getElementById("getBtnFetch");
    const putBtnFetch = document.getElementById("putBtnFetch");
    const deleteBtnFetch = document.getElementById("deleteBtnFetch");

    var elem = document.getElementsByName("chosen_api");

    for (var i = 0; i < elem.length; i++) {
        elem[i].onchange = function () {

            if (this.value === 'XMLH') {

                // document.getElementById("response").innerHTML = "";

                document.getElementById("postBtn").removeAttribute("hidden");
                document.getElementById("getBtn").removeAttribute("hidden");
                document.getElementById("putBtn").removeAttribute("hidden");
                document.getElementById("deleteBtn").removeAttribute("hidden");

                document.getElementById("postBtnFetch").setAttribute("hidden", "hidden");
                document.getElementById("getBtnFetch").setAttribute("hidden", "hidden");
                document.getElementById("putBtnFetch").setAttribute("hidden", "hidden");
                document.getElementById("deleteBtnFetch").setAttribute("hidden", "hidden");

                // user clicks POST button.
                postBtn.addEventListener("click", sendData);

                // user clicks GET button.
                getBtn.addEventListener("click", sendRequest);

                // user clicks PUT button.
                putBtn.addEventListener("click", sendUpdate);

                // user clicks DELETE button.
                deleteBtn.addEventListener("click", sendDelete);

            } else {

                // document.getElementById("response").innerHTML = "";

                document.getElementById("postBtnFetch").removeAttribute("hidden");
                document.getElementById("getBtnFetch").removeAttribute("hidden");
                document.getElementById("putBtnFetch").removeAttribute("hidden");
                document.getElementById("deleteBtnFetch").removeAttribute("hidden");

                document.getElementById("postBtn").setAttribute("hidden", "hidden");
                document.getElementById("getBtn").setAttribute("hidden", "hidden");
                document.getElementById("putBtn").setAttribute("hidden", "hidden");
                document.getElementById("deleteBtn").setAttribute("hidden", "hidden");

                // user clicks POST button.
                postBtnFetch.addEventListener("click", fetchData);

                // user clicks GET button.
                getBtnFetch.addEventListener("click", fetchRequest);

                // // user clicks PUT button.
                putBtnFetch.addEventListener("click", fetchUpdate);

                // user clicks DELETE button.
                deleteBtnFetch.addEventListener("click", fetchDelete);
            }
        }
    }
}

function handleResponse(xhr) {

    if (xhr.readyState == 4 && xhr.status == 200) {

        // populate the page with received data.
        document.getElementById("response").innerHTML = xhr.responseText;
    }
}

function setTime() {

    var date = new Date().toLocaleString();
    document.getElementById("date_record").value = date;
}

// POST.
function sendData() {

    // create XHR.
    let xhr = new XMLHttpRequest();

    // current date and time of the post generated by JavaScript call.
    setTime();
    // 100 - 103: refactor form data concept
    let recordID = document.getElementById("ID_record").value;
    let articleTitle = document.getElementById("article_name").value;
    let articleBody = document.getElementById("article_body").value;
    let date = document.getElementById("date_record").value;

    let payload = `id=${recordID}&title=${articleTitle}&article_body=${articleBody}&date_record=${date}`;

    if (xhr) {

        xhr.open("POST", "https://httpbin.org/post", true);
        xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
        xhr.onload = function () { handleResponse(xhr); };
        xhr.send(payload);
    }
}

// GET.
function sendRequest() {

    // create XHR.
    let xhr = new XMLHttpRequest();

    // current date and time of the post generated by JavaScript call.
    setTime();

    // document.getElementById("myForm").setAttribute("method", "GET"); // need?
    // document.getElementById("myForm").setAttribute("action", "https://httpbin.org/get"); // need?

    let recordID = document.getElementById("ID_record").value;
    let articleTitle = document.getElementById("article_name").value;
    let articleBody = document.getElementById("article_body").value;
    let date = document.getElementById("date_record").value;

    let payload = `id=${recordID}&title=${articleTitle}&article_body=${articleBody}&date_record=${date}`;

    if (xhr) {

        xhr.open("GET", "https://httpbin.org/get" + "?" + payload, true);
        xhr.onload = function () { handleResponse(xhr); };
        xhr.send(null);
    }
}

// PUT.
function sendUpdate() {

    // create XHR.
    let xhr = new XMLHttpRequest();

    // current date and time of the post generated by JavaScript call.
    setTime();

    let recordID = document.getElementById("ID_record").value;
    let articleTitle = document.getElementById("article_name").value;
    let articleBody = document.getElementById("article_body").value;
    let date = document.getElementById("date_record").value;

    let payload = `id=${recordID}&title=${articleTitle}&article_body=${articleBody}&date_record=${date}`;

    if (xhr) {

        xhr.open("PUT", "https://httpbin.org/put", true);
        xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
        xhr.onload = function () { handleResponse(xhr); };
        xhr.send(payload);
    }
}

// DELETE.
function sendDelete() {

    // create XHR.
    let xhr = new XMLHttpRequest();

    // current date and time of the post generated by JavaScript call.
    setTime();

    let recordID = document.getElementById("ID_record").value;
    let articleTitle = document.getElementById("article_name").value;
    let articleBody = document.getElementById("article_body").value;
    let date = document.getElementById("date_record").value;

    let payload = `id=${recordID}&title=${articleTitle}&article_body=${articleBody}&date_record=${date}`;

    if (xhr) {

        xhr.open("DELETE", "https://httpbin.org/delete" + "?" + payload, true);
        xhr.onload = function () { handleResponse(xhr); };
        xhr.send(null);
    }
}

// FETCH functions.

// POST.
function fetchData() {

    setTime();

    const data = {
        article_body: document.getElementById("article_body").value,
        date_record: document.getElementById("date_record").value,
        id: document.getElementById("ID_record").value,
        title: document.getElementById("article_name").value
    };

    fetch("https://httpbin.org/post", {
        method: "POST",
        headers: {
            "Content-Type": "application/x-www-form-urlencoded",
        },
        body: JSON.stringify(data),
    })
        .then((response) => response.text())
        .then((data) => {
            document.getElementById("response").innerHTML = data;
        })
        .catch((error) => {
            console.error("Error:", error);
        });
}

// GET.
function fetchRequest() {

    setTime();

    let recordID = document.getElementById("ID_record").value;
    let articleTitle = document.getElementById("article_name").value;
    let articleBody = document.getElementById("article_body").value;
    let date = document.getElementById("date_record").value;

    let payload = `id=${recordID}&title=${articleTitle}&article_body=${articleBody}&date_record=${date}`;

    fetch("https://httpbin.org/get" + "?" + payload, {
        method: "GET"
    })
        .then((response) => response.text())
        .then((data) => {
            document.getElementById("response").innerHTML = data;
        })
        .catch((error) => {
            console.error("Error:", error);
        });
}

// PUT.
function fetchUpdate() {

    setTime();

    const data = {
        article_body: document.getElementById("article_body").value,
        date_record: document.getElementById("date_record").value,
        id: document.getElementById("ID_record").value,
        title: document.getElementById("article_name").value
    };

    fetch("https://httpbin.org/put", {
        method: "PUT",
        headers: {
            "Content-Type": "application/x-www-form-urlencoded",
        },
        body: JSON.stringify(data),
    })
        .then((response) => response.text())
        .then((data) => {
            document.getElementById("response").innerHTML = data;
        })
        .catch((error) => {
            console.error("Error:", error);
        });
}

// DELETE.
function fetchDelete() {

    setTime();

    let recordID = document.getElementById("ID_record").value;
    let articleTitle = document.getElementById("article_name").value;
    let articleBody = document.getElementById("article_body").value;
    let date = document.getElementById("date_record").value;

    let payload = `id=${recordID}&title=${articleTitle}&article_body=${articleBody}&date_record=${date}`;

    fetch("https://httpbin.org/delete" + "?" + payload, {
        method: "DELETE"
    })
        .then((response) => response.text())
        .then((data) => {
            document.getElementById("response").innerHTML = data;
        })
        .catch((error) => {
            console.error("Error:", error);
        });
}